### ISSUE TITLE
How to use my ubuntu server Ipsec VPN tunnel to access other windows server in my Google cloud

### ISSUE THREAD

**Issue by ibragullam** [ryuichiueda/ros_setup_scripts_Ubuntu18.04_server#1]
Hi there am using Google Cloud i have created tow server inside, windows server and Ubuntu server 18.04  i have already configure ipsec vpn tunnel in mu ubuntu - server, now am trying to connect my windows server to be access by using the same ipsec vpn tunnel instead of using my windows server ips

**Comment by ryuichiueda** [comment]
This repository is providing install scripts for Robot Operating System. So your question maybe inappropriate here.
